# Generated by Django 5.1.15 on 2026-09-12 17:22

import bookings.models
import core.storages
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('rental_mode', models.CharField(choices=[('nightly', 'Nuit'), ('monthly', 'Mois'), ('yearly', 'Année')], max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guests', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='pending', max_length=12)),
                ('quoted_units', models.PositiveSmallIntegerField(default=1, help_text='Nuits ou mois')),
                ('quoted_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quoted_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quoted_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quoted_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quoted_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expires_at', models.DateTimeField()),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='listings.property')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de réservation',
                'verbose_name_plural': 'demandes de réservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('rental_mode', models.CharField(choices=[('nightly', 'Nuit'), ('monthly', 'Mois'), ('yearly', 'Année')], max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_payer', models.CharField(help_text='traveler | host', max_length=8)),
                ('status', models.CharField(choices=[('awaiting_deposit', 'Acompte en attente'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='awaiting_deposit', max_length=20)),
                ('contract_pdf', models.FileField(blank=True, null=True, storage=core.storages.private_storage, upload_to=bookings.models.contract_upload_to)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_bookings', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='listings.property')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.bookingrequest')),
            ],
            options={
                'verbose_name': 'réservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=24)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TND', max_length=3)),
                ('kind', models.CharField(choices=[('deposit', 'Acompte'), ('balance', 'Solde'), ('refund', 'Remboursement')], max_length=8)),
                ('status', models.CharField(choices=[('initiated', 'Initié'), ('succeeded', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='initiated', max_length=10)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_bo_status_6a8e57_idx'),
        ),
    ]
