# Generated by Django 5.1.15 on 2026-09-12 17:22

import availability.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
        ('bookings', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ical_url', models.URLField(max_length=500)),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('other', 'Autre')], default='other', max_length=8)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_calendars', to='listings.property')),
            ],
            options={
                'verbose_name': 'calendrier externe',
                'unique_together': {('property', 'ical_url')},
            },
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('kind', models.CharField(choices=[('booked', 'Réservé'), ('blocked_by_host', "Bloqué par l'hôte"), ('external_ical', 'Calendrier externe'), ('maintenance', 'Maintenance')], max_length=16)),
                ('external_uid', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='bookings.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='listings.property')),
                ('external_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='availability.externalcalendar')),
            ],
            options={
                'verbose_name': 'indisponibilité',
                'ordering': ['start'],
                'indexes': [models.Index(fields=['property', 'start', 'end'], name='availabilit_propert_ce3f45_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='availability_end_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('kind', 'booked')), expressions=[(availability.models.DateRange('start', 'end', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('property', '=')], name='availability_no_overlapping_bookings')],
            },
        ),
    ]
