# Generated by Django 5.1.15 on 2026-09-12 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('tayara', 'Tayara'), ('mubawab', 'Mubawab'), ('facebook', 'Facebook'), ('manual', 'Manuel')], default='manual', max_length=10)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('visit_scheduled', 'Visite planifiée'), ('converted', 'Converti'), ('rejected', 'Rejeté')], default='new', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='listings.property')),
            ],
            options={
                'verbose_name': 'lead',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('source_url',), name='lead_unique_source_url')],
            },
        ),
    ]
