# Generated by Django 5.2.17 on 2026-09-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='cgu, confidentialite, contact', max_length=40, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(help_text='Markdown : titres (##), paragraphes, listes (-), gras (**).')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'contenu du site',
                'verbose_name_plural': 'contenus du site',
                'ordering': ['key'],
            },
        ),
    ]
