# Generated by Django 5.1.15 on 2026-09-12 17:22

import core.storages
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import listings.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(help_text="Nom d'icône lucide côté front", max_length=40)),
                ('category', models.CharField(choices=[('essential', 'Essentiels'), ('comfort', 'Confort'), ('building', 'Immeuble'), ('safety', 'Sécurité')], default='comfort', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'équipement',
                'verbose_name_plural': 'équipements',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('studio', 'Studio'), ('apartment', 'Appartement'), ('villa', 'Villa'), ('room_in_shared_flat', 'Chambre en colocation')], max_length=24)),
                ('rooms_label', models.CharField(blank=True, help_text='S+1, S+2, ...', max_length=8)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('surface_m2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('has_elevator', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=True)),
                ('address_private', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('location_precision', models.CharField(choices=[('exact', 'Exacte'), ('approximate', 'Approximative')], default='approximate', max_length=12)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En attente de validation'), ('needs_visit', 'Visite à planifier'), ('published', 'Publié'), ('paused', 'En pause'), ('rejected', 'Rejeté')], db_index=True, default='draft', max_length=16)),
                ('verification_level', models.CharField(choices=[('verified', 'Vérifié'), ('selection', 'Sélection Loka')], default='verified', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Interne, jamais exposé')),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('visit_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('condition_grade', models.CharField(choices=[('basic', 'Simple'), ('good', 'Bon état'), ('excellent', 'Excellent')], default='good', max_length=12)),
                ('charges_included', models.BooleanField(default=False)),
                ('monthly_charges_estimate', models.DecimalField(blank=True, decimal_places=0, help_text='TND / mois', max_digits=8, null=True)),
                ('deposit_months', models.PositiveSmallIntegerField(default=1, help_text='Caution en nombre de mois de loyer (mensuel / annuel)')),
                ('min_lease_months', models.PositiveSmallIntegerField(default=1)),
                ('distance_notes', models.JSONField(blank=True, default=dict, help_text='{"ESPRIT": "8 min à pied", "Métro Ligne 2": "5 min"}')),
                ('house_rules', models.JSONField(blank=True, default=dict, help_text='{"smoking": false, "pets": false, "parties": false}')),
                ('meta_title', models.CharField(blank=True, max_length=120)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='geo.city')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='geo.neighborhood')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bien',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
            ],
            options={
                'unique_together': {('property', 'amenity')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, through='listings.PropertyAmenity', to='listings.amenity'),
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('original', models.ImageField(storage=core.storages.private_storage, upload_to=listings.models.photo_original_upload_to)),
                ('variants', models.JSONField(blank=True, default=dict, help_text='{"card": "url", ...}')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('taken_by_team', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.property')),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_mode', models.CharField(choices=[('nightly', 'Nuit'), ('monthly', 'Mois'), ('yearly', 'Année')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, help_text='TND', max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_duration', models.PositiveSmallIntegerField(default=1, help_text='Nuits (nightly) ou mois (monthly). Ignoré pour yearly (12).')),
                ('max_duration', models.PositiveSmallIntegerField(blank=True, help_text='Nuits ou mois. Vide = pas de maximum.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='listings.property')),
            ],
            options={
                'verbose_name': 'plan tarifaire',
                'ordering': ['rental_mode'],
                'unique_together': {('property', 'rental_mode')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'status'], name='listings_pr_city_id_87af72_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['neighborhood', 'status'], name='listings_pr_neighbo_6118b3_idx'),
        ),
    ]
