# Generated by Django 5.2.17 on 2026-09-13 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='published_snapshot',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='TND par nuit, par mois, ou par an pour le plan annuel (ADR 0007)', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
